#!/usr/bin/node

fs = require("fs");

const {countAttr, ff, mkDirObj, searchFsObj, searchDirObjs, m4aFile, mp3File } = require("./modules.js");

if(process.argv[2])
{
    if (process.env.APPLAIZ_DBG) console.error(process.argv[2]);

    console.log(
	JSON.stringify(
	    ff(
		{
		    lobj:JSON.parse(fs.readFileSync(process.argv[2])),
		    fMassage: (obj, patth, parent) => { //give every directory
			obj.path = patth;     // a dot-numeric path
			obj.parent = parent;  // and a parent so we can go back
		    },
		    // Test that fFile() is working by popping
		    // a couple of files and
		    // comparing output to input
		    fFile:(x)=>{x.files.pop();x.files.pop()},
		    // fDir() - test for existence of each dirname
		    fDir:(x,y)=>{
			if (process.env.APPLAIZ_DBG)
			    console.error(
				{"fDir-x":x.dirname,
				 "fDir-y":y.dirname},
				fs.existsSync(y.dirname)
			    )}
		}
	    ), null, 1
	)
    )
} else {
    console.error("Input is supposed to be a file generated by fsObj.js")
}
