#!/usr/bin/node

fs = require("fs");

function ff ({
    robj = {}, //robj is local (parameter)
    patth = ".",
    parent = "",
    fMassage = ()=>{},
    fFile = ()=>{},
    fDir = ()=>{}
}) 
{
    if (process.env.APPLAIZ_DBG) console.error(
	{"dirname":robj.dirname,"path":patth}
    );

    fMassage(robj,patth,parent);

    // fFile could, e. g., sort the filenames case-insensitively
    // or, as in countAttr(), count file attributes

    if (robj.files.length > 0) {
	fFile(robj)
    }		

    //fDir could, e. g. add a paths object to the directory object

    for (let i =0; i < robj.directories.length; i++) {
	let x = robj.directories[i];
	if(x) {
	    fDir(robj,x);
	    let z;
	    if (robj.path=="."){  z = ""} else z = robj.path;

	    ff({
		robj: x,
		patth: z + "." + i,
		parent: robj.path,
		fMassage: fMassage,
		fFile: fFile,
		fDir: fDir,
	    })

	    if (process.env.APPLAIZ_DBG) console.error({"directory":i});
	}
    }
    return robj;
}

if(process.argv[2])
{
    if (process.env.APPLAIZ_DBG) console.error(process.argv[2]);

    console.log(
	JSON.stringify(
	    ff(
		{
		    robj:JSON.parse(fs.readFileSync(process.argv[2])),
		    fMassage: (obj, patth, parent) => { //give every directory
			obj.path = patth;     // a dot-numeric path
			obj.parent = parent;  // and a parent so we can go back
		    },
		    // Test that fFile() is working by popping
		    // a couple of files and
		    // comparing output to input
		    fFile:(x)=>{x.files.pop();x.files.pop()},
		    // fDir() - test for existence of each dirname
		    fDir:(x,y)=>{
			if (process.env.APPLAIZ_DBG)
			    console.error(
				{"fDir-x":x.dirname,
				 "fDir-y":y.dirname},
				fs.existsSync(y.dirname)
			    )}
		}
	    ), null, 1
	)
    )
} else {
    console.error("Input is supposed to be a file generated by fsObj.js")
}
